### ISSUE TITLE
Not works on Ipad

### ISSUE THREAD

**Issue by gery** [ttulka/2d-videogame-in-assemblyscript#2]
Project is great anyway ;)

**Comment by ttulka** [comment]
Thanks!
I don't have an iPad, but I guess the problem is that it runs the module in Safari. Safari supports `WebAssembly.instantiateStreaming` starting with the [version 15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming).

You can fix this for the older Safari version by loading the WA module [without streaming](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API#loading_our_wasm_module_without_streaming).

However, as this is just an example project, I stick with `instantiateStreaming` here.

Cheers

**Comment by gery** [comment]
Thanks, I will get IOS 15 update in few days, and I will test it on Ipad air 3

**Comment by gery** [comment]
Works with IOS 15 ;)

**Comment by ttulka** [comment]
@gery cool, thanks for the feedback!
